// Auto-generated by scripts/split-writeups.mjs
// DO NOT edit manually — add new writeups to the event files in ./events/

import { bhackariWriteups } from './events/bhackari';
import { byuctfWriteups } from './events/byuctf';
import { citctfWriteups } from './events/citctf';
import { cyberbreakerQualWriteups } from './events/cyberbreaker_qual';
import { dalCtf2026Writeups } from './events/dal_ctf_2026';
import { flagyardWriteups } from './events/flagyard';
import { gpnctf2026Writeups } from './events/gpnctf_2026';
import { hacktheboxWriteups } from './events/hackthebox';
import { incognitoWriteups } from './events/incognito';
import { intechfestWriteups } from './events/intechfest';
import { jerseyctfWriteups } from './events/jerseyctf';
import { k1nd4susCtfWriteups } from './events/k1nd4sus_ctf';
import { kubsctfWriteups } from './events/kubsctf';
import { lagWriteups } from './events/lag';
import { lakeCtf2025Writeups } from './events/lake_ctf_2025';
import { ramWriteups } from './events/ram';
import { squ1rrelCtfWriteups } from './events/squ1rrel_ctf';
import { texsawCtfWriteups } from './events/texsaw_ctf';
import { thcon2026Writeups } from './events/thcon_2026';
import { them2026Writeups } from './events/them_2026';
import { tjcscWriteups } from './events/tjcsc';
import { vuwctf2025Writeups } from './events/vuwctf_2025';
import { boroCtfWriteups } from './events/boro_ctf';
import { siebersecCtfWriteups } from './events/siebersec_ctf';

export type { WriteUp, Category, Difficulty, MathFormula, TerminalOutput } from './types';

export const writeups: WriteUp[] = [
  ...bhackariWriteups,
  ...byuctfWriteups,
  ...citctfWriteups,
  ...cyberbreakerQualWriteups,
  ...dalCtf2026Writeups,
  ...flagyardWriteups,
  ...gpnctf2026Writeups,
  ...hacktheboxWriteups,
  ...incognitoWriteups,
  ...intechfestWriteups,
  ...jerseyctfWriteups,
  ...k1nd4susCtfWriteups,
  ...kubsctfWriteups,
  ...lagWriteups,
  ...lakeCtf2025Writeups,
  ...ramWriteups,
  ...squ1rrelCtfWriteups,
  ...texsawCtfWriteups,
  ...thcon2026Writeups,
  ...them2026Writeups,
  ...tjcscWriteups,
  ...vuwctf2025Writeups,
  ...boroCtfWriteups,
  ...siebersecCtfWriteups,
];
